application: hilite-me
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: vnd.microsoft.icon

- url: /.*
  script: main.py
